// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSlzCwE0j75PgOB8s8BRzx1pX4UNxX06k',
    appId: '1:1069560030848:web:b2cd61054c634879a32865',
    messagingSenderId: '1069560030848',
    projectId: 'ctoc-cd462',
    authDomain: 'ctoc-cd462.firebaseapp.com',
    storageBucket: 'ctoc-cd462.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCsop5ZcFrhJrl1oxg7y6DcsfTsxlY12wc',
    appId: '1:1069560030848:android:66d6c4eef6c18a62a32865',
    messagingSenderId: '1069560030848',
    projectId: 'ctoc-cd462',
    storageBucket: 'ctoc-cd462.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgKMb7eDoD3KZ3GGSwxKGbNKrsYJPenpQ',
    appId: '1:1069560030848:ios:5ad70f03b491dab4a32865',
    messagingSenderId: '1069560030848',
    projectId: 'ctoc-cd462',
    storageBucket: 'ctoc-cd462.appspot.com',
    androidClientId: '1069560030848-52gbql43ee470pgqg03qugaa73usmbrd.apps.googleusercontent.com',
    iosClientId: '1069560030848-c52afb6m6jvdcef930ntc6h0ed483mt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgKMb7eDoD3KZ3GGSwxKGbNKrsYJPenpQ',
    appId: '1:1069560030848:ios:5ad70f03b491dab4a32865',
    messagingSenderId: '1069560030848',
    projectId: 'ctoc-cd462',
    storageBucket: 'ctoc-cd462.appspot.com',
    androidClientId: '1069560030848-52gbql43ee470pgqg03qugaa73usmbrd.apps.googleusercontent.com',
    iosClientId: '1069560030848-c52afb6m6jvdcef930ntc6h0ed483mt1.apps.googleusercontent.com',
    iosBundleId: 'com.example.ctoc',
  );
}
